se agrego el footer
castromaciel/Drugstore-Front pull request #1
Opened 2021-10-28 01:51 UTC by RamiroNieva

2021-10-31 17:58 UTC, castromaciel requested changes
Trata de no agregar nada en el archivo src/index.js.
Deja los componentes listos, Pero no agregues nignuno al index.js

2021-11-01 17:09 UTC, Nidev-lab commented on src/components/Footer/Footer.js
> +function Footer() {
Configura la identacion como la tiene el proyecto.

2021-11-01 17:13 UTC, Nidev-lab commented
El nombre de la rama debe dar un indicio de la funcionalidad que estas trabajando. Fijate como estan nombrando sus ramas Maciel y Carlos y ponele un nombre adecuado a la tuya. Podria ser algo como: feature/footer o utilizar el codigo de tu tarjeta en trello incluso. Pero rama-rami, no es correcto.

2021-11-04 19:07 UTC, Nidev-lab commented
Este pr lo cierro porque ya se agrego la feature en otra pr

2021-11-04 19:09 UTC, closed without merging